services:
  lemonade:
    image: ghcr.io/lemonade-sdk/lemonade-server:v11.9.0
    environment:
      LEMONADE_ALLOWED_ORIGINS: "*"
    ports:
      - "13305:13305"
    volumes:
      # Persist downloaded models
      - lemonade-cache:/opt/lemonade/.cache/huggingface
      # Persist llama binaries
      - lemonade-llama:/opt/lemonade/llama
      # Persist model options and other backend binaries
      - lemonade-recipe:/opt/lemonade/.cache/lemonade
    restart: unless-stopped

volumes:
  lemonade-cache:
  lemonade-llama:
  lemonade-recipe:
